FROM jenkins:alpine

USER root

RUN apk update && apk add git && apk add --update ca-certificates openssl && update-ca-certificates
RUN wget https://raw.github.com/petervanderdoes/gitflow-avh/develop/contrib/gitflow-installer.sh && sh gitflow-installer.sh install stable; rm gitflow-installer.sh


USER jenkins

